dwitter/urls.py
from django.urls import path
from .views import dashboard, profile_list,profile,homepage,register

app_name = "dwitter"

urlpatterns = [
    path("",homepage,name="homepage"),
    path("dashboard/", dashboard, name="dashboard"),
    path("profile_list/", profile_list, name="profile_list"),
    path("profile/<int:pk>", profile, name="profile"),
    path("register/",register,name="register"),
]

social/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('accounts/',include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
    path("", include("dwitter.urls")),
    
]

dwitter/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    follows = models.ManyToManyField(
        "self",
        related_name="followed_by",
        symmetrical=False,
        blank=True
    )

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance)
        user_profile.save()
        user_profile.follows.add(instance.profile)
        user_profile.save()

class Dweet(models.Model):
    user = models.ForeignKey(User,
                             related_name="dweets",
                             on_delete=models.DO_NOTHING)
    body = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return (
            f"{self.user} "
            f"({self.created_at:%Y-%m-%d %H:%M}): "
            f"{self.body[:30]}..."
        )

dwitter/forms.py
from django import forms
from .models import Dweet
from django.contrib.auth.forms import UserCreationForm

class DweetForm(forms.ModelForm):
    body = forms.CharField(
        required=True,
        widget=forms.widgets.Textarea(
            attrs={
                "placeholder": "Say something...",
                "class": "textarea is-success is-medium",
            }
        ),
        label="",
    )

    class Meta:
        model = Dweet
        exclude = ("user", )

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ("email",)

dwitter/views.py
from django.shortcuts import render,redirect
from .models import Profile,Dweet
from .forms import DweetForm,CustomUserCreationForm
from django.contrib.auth import login
from django.urls import reverse
from django.contrib import messages

# Create your views here.
def homepage(request):
    return render(request, "dwitter/homepage.html")

def dashboard(request):
    form = DweetForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            dweet = form.save(commit=False)
            dweet.user = request.user
            dweet.save()
            return redirect("dwitter:dashboard")

    followed_dweets = Dweet.objects.filter(
        user__profile__in=request.user.profile.follows.all()
    ).order_by("-created_at")

    return render(
        request,
        "dwitter/dashboard.html",
        {"form": form, "dweets": followed_dweets},
    )

def profile_list(request):
    profiles = Profile.objects.exclude(user=request.user)
    return render(request, "dwitter/profile_list.html", {"profiles": profiles})


def profile(request, pk):
    if not hasattr(request.user, 'profile'):
        missing_profile = Profile(user=request.user)
        missing_profile.save()

    profile = Profile.objects.get(pk=pk)
    if request.method == "POST":
        current_user_profile = request.user.profile
        data = request.POST
        action = data.get("follow")
        if action == "follow":
            current_user_profile.follows.add(profile)
        elif action == "unfollow":
            current_user_profile.follows.remove(profile)
        current_user_profile.save()
    return render(request, "dwitter/profile.html", {"profile": profile})

def register(request):
    if request.method == "GET":
        return render(
            request, "dwitter/register.html",
            {"form": CustomUserCreationForm}
        )
    elif request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, "Registration successful." )
            return redirect(reverse("dwitter:dashboard"))

dwitter/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Include the Bulma CSS framework for styling -->
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <title>Tiny</title>
</head>
<body>
    {% if user.is_authenticated %}
        <a href="{% url 'dwitter:dashboard' %} ">
    {% else %}
        <a href ="#">
    {% endif %}
    <section class="hero is-small is-success mb-4">
        <div class="hero-body">
            <h1 class="title is-1" style="display:inline">Tiny</h1>
            <p class="subtitle is-4" style="display:inline">
                A tiny social network built with Django
            </p>
            {% if user.is_authenticated %}
                <nav class="navbar">
                    <div class="container">
                    <div id="navbarMenu" class="navbar-menu">
                        <div class="navbar-end">
                        <a class="navbar-item is-size-5 has-text-weight-semibold" href="{% url 'dwitter:dashboard' %}">
                            Home
                        </a>
                        <a class="navbar-item is-size-5 has-text-weight-semibold" href="{% url 'password_change' %} ">
                            Password Change
                        </a>
                        <a class="navbar-item is-size-5 has-text-weight-semibold" href="{% url 'logout' %}">
                            Logout
                        </a>
                        </div>
                    </div>
                    </div>
                </nav>
            {% else %}
                <nav class="navbar">
                    <div class="container">
                    <div id="navbarMenu" class="navbar-menu">
                        <div class="navbar-end">
                        <a class="navbar-item is-size-5 has-text-weight-semibold" href="{% url 'login' %}">
                            Login
                        </a>
                        <a class="navbar-item is-size-5 has-text-weight-semibold">
                            Contact Us
                        </a>
                        </div>
                    </div>
                    </div>
                </nav>
            {% endif %}
        </div>
    </section>
    </a>
    <div class="container">
        {% if user.is_authenticated %}
            <div class="columns">
                {% block content %}

                {% endblock content %}
            </div>
        {% else %}
            <div>
                {% block info %}

                {% endblock info %}
            </div>
        {% endif %}
    </div>
</body>
</html>

dwitter/templates/dwitter/dashboard.html
{% extends 'base.html' %}

{% block content %}

<div class="column">
    {% for dweet in dweets %}
    <div class="box">
        {{dweet.body}}
        <span class="is-small has-text-grey-light">
            {{ dweet.created_at }} by {{ dweet.user.username }}
        </span>
    </div>
{% endfor %}
</div>

<div class="column is-one-third">

    <div class="block">
        <a href="{% url 'dwitter:profile_list' %} ">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
    </div>

    <div class="block">
        <a href="{% url 'dwitter:profile' request.user.profile.id %} ">
            <button class="button is-success is-light is-outlined is-fullwidth">
                My Profile
            </button>
        </a>
    </div>

    <div class="block">
        <div class="block">
            <h2 class="title is-2">Speak Your Mind</p>
        </div>
        <div class="block">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="button is-success is-fullwidth is-medium mt-5"
                        type="submit">Post
                </button>
            </form>
        </div>
    </div>

</div>

{% endblock content %}

dwitter/templates/dwitter/homepage.html
{% extends 'base.html' %}

{% block info%}
    <section class="hero is-fullheight is-default is-bold">
        <div class="hero-body">
            <div class="container has-text-centered">
                <div class="columns is-vcentered">
                    <div class="column is-5">
                        <figure class="image is-4by3">
                            <img src="https://cdn.searchenginejournal.com/wp-content/uploads/2021/09/16-reasons-why-social-media-is-important-to-your-company-616d3200e6dc6-sej.png" alt="Description">
                        </figure>
                    </div>
                    <div class="column is-6 is-offset-1">
                        <h1 class="title is-2">
                            What is Tiny? 
                        </h1>
                        <h2 class="subtitle is-4">
                            Connect with purpose, real connections, real people,your life, and your stories
                        </h2>
                        <br>
                        <p class="has-text-centered">
                            <a class="button is-medium is-info is-outlined" href="{% url 'dwitter:register' %}">
                                Sign Up
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock info %}

dwitter/templates/dwitter/profile.html
{% extends 'base.html' %}

{% block content %}

<div class="column">

    <div class="block">
    <h1 class="title is-1">
        {{profile.user.username|upper}}'s Post
    </h1>

    <form method="post">
        {% csrf_token %}
        <div class="buttons has-addons">
        {% if profile in user.profile.follows.all %}
            <button class="button is-success is-static">
                Follow
            </button>
            <button class="button is-danger"
                    name="follow"
                    value="unfollow">
                Unfollow
            </button>
        {% else %}
            <button class="button is-success"
                    name="follow"
                    value="follow">
                Follow
            </button>
            <button class="button is-danger is-static">
                Unfollow
            </button>
        {% endif %}
        </div>
    </form>
    </div>

    <div class="content">
        {% for dweet in profile.user.dweets.all %}
            <div class="box">
                {{ dweet.body }}
                <span class="is-small has-text-grey-light">
                    ({{ dweet.created_at }})
                </span>
            </div>
        {% endfor %}
    </div>

</div>

<div class="column is-one-third">

    <div class="block">
        <a href="{% url 'dwitter:profile_list' %}">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} follows:
        </h3>
        <div class="content">
            <ul>
            {% for following in profile.follows.all %}
                <li>
                    <a href="{% url 'dwitter:profile' following.id %}">
                        {{ following }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} is followed by:
        </h3>
        <div class="content">
            <ul>
            {% for follower in profile.followed_by.all %}
                <li>
                    <a href="{% url 'dwitter:profile' follower.id %}">
                        {{ follower }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>

</div>

{% endblock content %}

dwitter/templates/dwitter/profile_list.html
{% extends 'base.html' %}

{% block content %}

<div class="column">

{% for profile in profiles %}

    <div class="block">
      <div class="card">
        <a href="{% url 'dwitter:profile' profile.id %}">
          <div class="card-content">
            <div class="media">
              <div class="media-left">
                <figure class="image is-48x48">
                  <img src="https://bulma.io/images/placeholders/96x96.png"
                       alt="Placeholder image">
                </figure>
              </div>
              <div class="media-content">
                <p class="title is-4">
                  {{ profile.user.username }}
                </p>
                <p class="subtitle is-6">
                  @{{ profile.user.username|lower }}
                </p>
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>

{% endfor %}

</div>

{% endblock content %}

dwitter/templates/dwitter/register.html
{% extends 'base.html' %}

{% block info %}
<style>
    label, input {
        display: block;
        width: 100%
    }
</style>
<div class ="column">
    <div class="hero is-fullheight">
        <div class="hero-body is-justify-content-center is-align-items-center">
            <div class="columns is-flex is-flex-direction-column box">
                <h1 class="title is-2" style="display:inline">Let's Get Started </h1>
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="column">
                            {{ field.errors }}
                            <div>
                                {{ field.label_tag }} {{ field }} 
                            </div>
                        </div>
                    {% endfor %}
                    <div class="column">
                        <button class="button is-primary is-fullwidth" type="submit">Sign Up</button>
                    </div>
                </form>
                <div class="has-text-centered">
                    <p class="is-size-7"> Already have an account? <a href="{% url 'login' %}" class="has-text-primary">Back to login</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock info %}